# Etapa 1: Construcción de la aplicación Angular
FROM node:18 AS builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json para instalar dependencias
COPY ./ /app/

# Instalar dependencias
RUN npm install

RUN npm install esbuild --save-dev

# Construir la aplicación en modo producción
RUN npm run build --prod

# Etapa 2: Servir la aplicación con Nginx
FROM nginx:alpine

# Copiar la aplicación compilada desde la etapa de construcción
COPY --from=builder /app/dist/frontend /usr/share/nginx/html

# Copiar archivo de configuración de Nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto donde correrá la app
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
