version: '3.8'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_data
      MYSQL_USER: my_user
      MYSQL_PASSWORD: test123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend_user:
    build:
      context: ../userService
      dockerfile: Dockerfile
    container_name: backend_user
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING:-Server=localhost;Database=user_data;User=root;Password=root_password;}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - NG_APP_ADDRESS=${NG_APP_ADDRESS:-backend_user}
    ports:
      - "80:80"
    
volumes:
  mysql_data:
  


