FROM python:3.9.18-bullseye

# Install dependencies
RUN apt-get update -y && apt-get install -y wget xvfb unzip jq

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install "fastapi[standard]"

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]