FROM python:3.9.18-slim

# Install dependencies
RUN apt-get update -y && apt-get install -y wget xvfb unzip jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install "fastapi[standard]" && \
    pip install python-jose[cryptography] && \
    rm -rf /root/.cache/pip

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]